# Version for moveit planning - moveit without rrc-driver
version: '2'
services:

  moveit-service:
    image: gramaziokohler/ros-noetic-dfab:22.05
    container_name: moveit-service
    environment:
      - ROS_HOSTNAME=moveit-service
      - ROS_MASTER_URI=http://ros-core:11311
      # GUI: To forward the GUI to an external X11 server (eg. XMing), uncomment the following line
      - DISPLAY=host.docker.internal:0.0
    depends_on:
      - ros-core
    volumes:
      - ./abb_irb2600_12_185_dual_config:/root/catkin_ws/src/abb_irb2600_12_185_dual_config
    command:
      - roslaunch
      - --wait
      - abb_irb2600_12_185_dual_config
      - demo.launch
      # To launch the RVIZ GUI, change the following to true
      - use_rviz:=false
      - pipeline:=ompl


  ros-core:
    image: gramaziokohler/ros-noetic-dfab:22.05
    container_name: ros-core
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-noetic-dfab:22.05
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-core:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-noetic-dfab:22.05
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-core:11311
    depends_on:
      - ros-core
    volumes:
      - ./abb_irb2600_12_185_dual_config:/root/catkin_ws/src/abb_irb2600_12_185_dual_config
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  # To use the web-based GUI, uncomment the following lines
  # gui:
  #   image: gramaziokohler/novnc:latest
  #   ports:
  #     - "8080:8080"